version: 2
jobs:
  build:
    docker:
      - image: ivigns/nice-linux:debian-0.0.3
    resource_class: xlarge
    working_directory: /work
    steps:
      - checkout
      - run:
          name: build
          command:
          - git submodule sync
          - git submodule update --init --recursive
          - cd /drone/src/libdivsufsort
          - git pull origin master
          - cd /drone/src/sdsl-lite
          - git pull origin master
          - cd /drone/src/sdsl-lite/external/libdivsufsort
          - git pull origin master
          - cd /drone/src/pybind11
          - git pull origin master
          - cd /tmp
          - mkdir sdsl-lite-build
          - mkdir libdivsufsort-build
          - export CC=clang
          - export CXX=clang++
          - export CFLAGS="-O3 -static -lc -fPIC -static-libgcc -pipe -fcolor-diagnostics -lpthread -Wl,-Bstatic"
          - cd /tmp/libdivsufsort-build
          - cmake -D BUILD_SHARED_LIBS=OFF /drone/src/libdivsufsort
          - make install
          - export CXXFLAGS="-O3 -pipe -fcolor-diagnostics -static-libgcc -static-libstdc++ -fPIC -lpthread  -Wl,-Bstatic -Wl,-Bdynamic"
          - cd /tmp/sdsl-lite-build
          - cmake /drone/src/sdsl-lite
          - make install
          - export CXXFLAGS="-O3 -pipe -stdlib=libc++ -fcolor-diagnostics -fPIC -DNOCROSSCONSTRUCTORS"
          - export CFLAGS="-O3 -pipe -fcolor-diagnostics -fPIC"
          - cd /drone/src/pybind11
          - pip install --no-binary ':all:' --no-cache-dir . --verbose
          - cd /drone/src
          - pip wheel --no-binary ':all:' --no-cache-dir -w dist . --verbose
      - run:
          name: show
          command: cd /work && ls -aR
      - run:
          name: test wheel
          command:
          - apt-get update -qq
          - apt-get install -qqy python python-pip
          - pip install $(ls -d /tmp/cache/dist/*)
          - mkdir /tmp/test
          - cd /tmp/test
          - python -c 'import pysdsl'
