version: 2
jobs:
  build:
    docker:
      - image: ivigns/nice-ubuntu:0.0.1
    resource_class: xlarge
    working_directory: /work
    steps:
      - checkout
      - run:
          name: Build pysdsl
          command: |
            git submodule sync
            git submodule update --init --recursive
            git submodule update --recursive
            cd /work/sdsl-lite
            bash unsinstall.sh /usr
            cd /tmp
            rm -rf sdsl-lite-build
            rm -rf libdivsufsort-build
            mkdir sdsl-lite-build
            mkdir libdivsufsort-build
            export CC=clang
            export CXX=clang++
            export CFLAGS="-O3 -pipe -fPIC"
            export CXXFLAGS="-O3 -pipe -fcolor-diagnostics -static-libgcc -fPIC -lpthread -Wl,-Bstatic -Wl,-Bdynamic"
            cd /tmp/libdivsufsort-build
            cmake /work/libdivsufsort
            make install
            export CXXFLAGS="${CXXFLAGS} -DNOCROSSCONSTRUCTORS"
            cd /tmp/sdsl-lite-build
            cmake /work/sdsl-lite
            make install
            cd /work/pybind11
            pip install --no-binary :all: --no-cache-dir . --verbose
            # cd /work
            # pip install --no-binary :all: --no-cache-dir . --verbose
      - run:
          name: Show
          command: cd /work && ls -aR
